services:
  web:
    image: nginx:alpine
    container_name: my_web_app
    ports:
      - "8080:80"
    volumes:
      - ./unit_frontend:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  backend:
    image: node:alpine
    container_name: my_backend_app
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./unit_backend:/app
    restart: unless-stopped
    command: sh -c "cd /app && npm install && npm run start"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
